import './globals.css'
import type { Metadata } from 'next'
import Navbar from "@/components/Navbar/Navbar"
import { Inter } from 'next/font/google'
import Provider from './Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pinterest Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <Navbar />
        {children}
        </Provider>
        </body>
    </html>
  )
}
